///|
let object_proto_ref : Ref[ObjectValue?] = Ref::new(None)

///|
let function_proto_ref : Ref[JSValue?] = Ref::new(None)

///|
fn object_proto() -> ObjectValue? {
  get_proto_ref(object_proto_ref)
}

///|
fn function_proto() -> JSValue? {
  get_value_ref(function_proto_ref)
}

///|
fn object_proto_for_env(env : Env) -> ObjectValue? {
  match global_object(env) {
    Some(global_obj) =>
      match global_obj.props.get("Object") {
        Some(prop) =>
          match prop.value {
            Builtin(builtin) =>
              match builtin.props.get("prototype") {
                Some(proto_prop) =>
                  match proto_prop.value {
                    Object(proto_obj) => Some(proto_obj)
                    _ => None
                  }
                None => None
              }
            _ => None
          }
        None => None
      }
    None => None
  }
}

///|
fn function_proto_for_env(env : Env) -> JSValue? {
  match global_object(env) {
    Some(global_obj) =>
      match global_obj.props.get("Function") {
        Some(prop) =>
          match prop.value {
            Builtin(builtin) =>
              match builtin.props.get("prototype") {
                Some(proto_prop) => Some(proto_prop.value)
                None => None
              }
            _ => None
          }
        None => None
      }
    None => None
  }
}

///|
fn function_ctor_for_env(env : Env) -> JSValue? {
  match global_object(env) {
    Some(global_obj) =>
      match global_obj.props.get("Function") {
        Some(prop) => Some(prop.value)
        None => None
      }
    None => None
  }
}
