///|
fn init_regexp_date_ctors(
  regexp_proto_obj : ObjectValue,
  regexp_proto_value : JSValue,
  date_proto_obj : ObjectValue,
  date_proto_value : JSValue,
  species_key : String,
  to_primitive_key : String,
) -> (JSValue, JSValue) {
  let regexp_ctor = new_builtin_value(BuiltinFunction::RegExpConstructor)
  match regexp_ctor {
    Builtin(builtin) => {
      builtin.props.set("prototype", property_data_const(regexp_proto_value))
      builtin.props.set(
        "escape",
        property_data_non_enum(new_builtin_value(BuiltinFunction::RegExpEscape)),
      )
      set_accessor_property_with_enum(
        builtin.props,
        species_key,
        Some(new_builtin_value(BuiltinFunction::SpeciesGetter)),
        None,
        false,
      )
    }
    _ => ()
  }
  regexp_proto_obj.props.set("constructor", property_data_non_enum(regexp_ctor))
  let date_ctor = new_builtin_value(BuiltinFunction::DateConstructor)
  match date_ctor {
    Builtin(builtin) => {
      builtin.props.set("prototype", property_data_const(date_proto_value))
      builtin.props.set(
        "parse",
        property_data_non_enum(new_builtin_value(BuiltinFunction::DateParse)),
      )
      builtin.props.set(
        "UTC",
        property_data_non_enum(new_builtin_value(BuiltinFunction::DateUTC)),
      )
      builtin.props.set(
        "now",
        property_data_non_enum(new_builtin_value(BuiltinFunction::DateNow)),
      )
    }
    _ => ()
  }
  date_proto_obj.props.set("constructor", property_data_non_enum(date_ctor))
  date_proto_obj.props.set(
    to_primitive_key,
    property_data_readonly(
      new_builtin_value(BuiltinFunction::DateSymbolToPrimitive),
    ),
  )
  (regexp_ctor, date_ctor)
}
