///|
fn init_function_ctor(function_proto_value : Value) -> Value {
  let function_ctor = new_builtin_value(BuiltinFunction::FunctionConstructor)
  match function_ctor {
    Builtin(builtin) =>
      props_set(
        builtin.props,
        "prototype",
        property_data_const(function_proto_value),
      )
    _ => ()
  }
  match function_proto_value {
    Function(func) =>
      props_set(
        func.props,
        "constructor",
        property_data_non_enum(function_ctor),
      )
    Builtin(builtin) =>
      props_set(
        builtin.props,
        "constructor",
        property_data_non_enum(function_ctor),
      )
    _ => ()
  }
  function_ctor
}

///|
fn init_generator_family_ctors(
  function_ctor : Value,
  generator_function_proto_obj : ObjectValue,
  async_generator_function_proto_obj : ObjectValue,
  async_function_proto_obj : ObjectValue,
) -> Unit {
  let generator_function_ctor = new_builtin_value(
    BuiltinFunction::GeneratorFunctionConstructor,
  )
  match generator_function_ctor {
    Builtin(builtin) => {
      rc_replace_optional_value(builtin.proto, Some(function_ctor))
      builtin.proto = Some(function_ctor)
      props_set(
        builtin.props,
        "prototype",
        property_data_const(Object(generator_function_proto_obj)),
      )
    }
    _ => ()
  }
  props_set(
    generator_function_proto_obj.props,
    "constructor",
    property_data_readonly(generator_function_ctor),
  )
  let async_generator_function_ctor = new_builtin_value(
    BuiltinFunction::AsyncGeneratorFunctionConstructor,
  )
  match async_generator_function_ctor {
    Builtin(builtin) => {
      rc_replace_optional_value(builtin.proto, Some(function_ctor))
      builtin.proto = Some(function_ctor)
      props_set(
        builtin.props,
        "prototype",
        property_data_const(Object(async_generator_function_proto_obj)),
      )
    }
    _ => ()
  }
  props_set(
    async_generator_function_proto_obj.props,
    "constructor",
    property_data_readonly(async_generator_function_ctor),
  )
  let async_function_ctor = new_builtin_value(
    BuiltinFunction::AsyncFunctionConstructor,
  )
  match async_function_ctor {
    Builtin(builtin) => {
      rc_replace_optional_value(builtin.proto, Some(function_ctor))
      builtin.proto = Some(function_ctor)
      props_set(
        builtin.props,
        "prototype",
        property_data_const(Object(async_function_proto_obj)),
      )
    }
    _ => ()
  }
  props_set(
    async_function_proto_obj.props,
    "constructor",
    property_data_readonly(async_function_ctor),
  )
}
