///|
let module_binding_target_key = "__module_binding_target"

///|
let module_binding_name_key = "__module_binding_name"

///|
let array_iter_target_key = "__array_iterator_target"

///|
let array_iter_index_key = "__array_iterator_index"

///|
let array_iter_kind_key = "__array_iterator_kind"

///|
let string_iter_target_key = "__string_iterator_target"

///|
let string_iter_index_key = "__string_iterator_index"

///|
let regexp_iter_regexp_key = "__regexp_iterator_regexp"

///|
let regexp_iter_string_key = "__regexp_iterator_string"

///|
let regexp_iter_global_key = "__regexp_iterator_global"

///|
let regexp_iter_unicode_key = "__regexp_iterator_unicode"

///|
let regexp_iter_done_key = "__regexp_iterator_done"

///|
let async_from_sync_iter_target_key = "__async_from_sync_iter_target"

///|
let async_from_sync_iter_next_key = "__async_from_sync_iter_next"
